/**
 * Which templates have a pre-generated static WebP in `public/thumbnails/`.
 *
 * GENERATED — do not hand-edit the array. `scripts/generate-template-thumbnails.ts`
 * rewrites it from what actually landed on disk after every run.
 *
 * WHY this exists: `TemplateCard` walks a source ladder (static WebP → on-demand
 * `/api/thumbnails/[id]` → live render). Without a manifest the card had to *probe*
 * the static file and rely on `onError` to fall through, which fired a real 404 per
 * template — ~99 red errors in the console on every visit to the Templates tab, plus
 * 99 wasted round trips. The card now starts at the first step that can actually
 * succeed, so a template with no pre-generated file never requests one.
 */
import { isThumbnailPending } from "./thumbnail-pending"

export const STATIC_THUMBNAIL_IDS: ReadonlySet<string> = new Set([
  "academiccv",
  "apex",
  "architect",
  "atelier",
  "ats",
  "atscardinal",
  "atscerulean",
  "atscobalt",
  "atscopper",
  "atsgarnet",
  "atsgraphite",
  "atsharbor",
  "atsmeridian",
  "atsnordic",
  "atsonyx",
  "atssable",
  "atssequoia",
  "atsslate",
  "atsverdant",
  "aurora",
  "banner",
  "bauhaus",
  "berlin",
  "bloom",
  "blueprintcv",
  "boldblock",
  "carbon",
  "cascade",
  "casual",
  "charcoalclassic",
  "chef",
  "circular",
  "classic",
  "classicmono",
  "cobalt",
  "communicator",
  "confetti",
  "consul",
  "copenhagen",
  "coral",
  "coralsidebar",
  "datadriven",
  "doctor",
  "duality",
  "editorial2",
  "editorialserif",
  "elegant",
  "elite-atlas",
  "elite-aura",
  "elite-cadence",
  "elite-counsel",
  "elite-cuvee",
  "elite-meridian",
  "elite-pulse",
  "engraved",
  "exec-citadel",
  "exec-cobalt",
  "exec-dynasty",
  "exec-nocturne",
  "exec-platine",
  "exec-porcelain",
  "exec-regency",
  "exec-sovereign",
  "fashion",
  "filmmaker",
  "fold",
  "frame",
  "geneva",
  "genevanoir",
  "glass",
  "havana",
  "helix",
  "horizontal",
  "journalist",
  "kyoto",
  "larsson",
  "legalbrief",
  "lisbon",
  "lumiere",
  "luxe-apex",
  "luxe-noir",
  "luxe-regent",
  "luxe-vellum",
  "luxurious",
  "metro",
  "milan",
  "minimal",
  "modern",
  "mosaic",
  "nautical",
  "navyexecutive",
  "neon",
  "nova",
  "onyx",
  "outline",
  "pearl",
  "photographer",
  "porto",
  "prism",
  "professional",
  "reykjavik",
  "risodesigner",
  "riviera",
  "rose",
  "sagebotanical",
  "sahara",
  "salespitch",
  "seoul",
  "sharp",
  "show-cameo",
  "show-marquis",
  "show-plume",
  "show-soiree",
  "sidebar",
  "spark",
  "stockholm",
  "stripe",
  "swissgrid",
  "teacher",
  "thompson",
  "timelinevertical",
  "tokyo",
  "translatorcv",
  "uxtokens",
  "velvet",
  "vertex",
  "vertical",
  "vienna",
  "vitae",
  "vogue",
  "windsor",
  "writer",
])

/** True when `public/thumbnails/<id>.webp` is known to exist. */
export function hasStaticThumbnail(templateId: string): boolean {
  // A redesigned template's photograph is a lie until it is re-shot, and a gallery that
  // shows the wrong design is worse than a heavier card. Pending ids fall through to the
  // live render of the real component. See lib/resume/thumbnail-pending.ts.
  if (isThumbnailPending(templateId)) return false
  return STATIC_THUMBNAIL_IDS.has(templateId)
}
