/**
 * Which templates have a pre-generated static WebP in `public/thumbnails/`.
 *
 * GENERATED — do not hand-edit the array. `scripts/generate-template-thumbnails.ts`
 * rewrites it from what actually landed on disk after every run.
 *
 * WHY this exists: `TemplateCard` walks a source ladder (static WebP → on-demand
 * `/api/thumbnails/[id]` → live render). Without a manifest the card had to *probe*
 * the static file and rely on `onError` to fall through, which fired a real 404 per
 * template — ~99 red errors in the console on every visit to the Templates tab, plus
 * 99 wasted round trips. The card now starts at the first step that can actually
 * succeed, so a template with no pre-generated file never requests one.
 */
export const STATIC_THUMBNAIL_IDS: ReadonlySet<string> = new Set([
  "academiccv",
  "apex",
  "architect",
  "atelier",
  "ats",
  "aurora",
  "banner",
  "barcelona",
  "bauhaus",
  "berlin",
  "bloom",
  "blueprintcv",
  "boldblock",
  "carbon",
  "cascade",
  "casual",
  "charcoalclassic",
  "chef",
  "circular",
  "classic",
  "classicmono",
  "cobalt",
  "communicator",
  "confetti",
  "consul",
  "copenhagen",
  "coral",
  "coralsidebar",
  "datadriven",
  "doctor",
  "duality",
  "dublin",
  "editorial2",
  "editorialserif",
  "elegant",
  "elite-atlas",
  "elite-aura",
  "elite-cadence",
  "elite-counsel",
  "elite-cuvee",
  "elite-meridian",
  "elite-pulse",
  "engraved",
  "exec-citadel",
  "exec-cobalt",
  "exec-dynasty",
  "exec-nocturne",
  "exec-oxblood",
  "exec-platine",
  "exec-porcelain",
  "exec-regency",
  "exec-sovereign",
  "exec-terra",
  "executive",
  "fashion",
  "filmmaker",
  "fold",
  "frame",
  "geneva",
  "genevanoir",
  "glass",
  "havana",
  "helix",
  "helsinki",
  "horizontal",
  "hotelcv",
  "journalist",
  "kyoto",
  "larsson",
  "legalbrief",
  "lisbon",
  "lumiere",
  "luxe-apex",
  "luxe-aurum",
  "luxe-noir",
  "luxe-regent",
  "luxe-vellum",
  "luxurious",
  "metro",
  "milan",
  "minimal",
  "modern",
  "mosaic",
  "nautical",
  "navyexecutive",
  "neon",
  "nova",
  "onyx",
  "outline",
  "pearl",
  "photographer",
  "porto",
  "prism",
  "professional",
  "psychologist",
  "reykjavik",
  "risodesigner",
  "riviera",
  "rose",
  "sagebotanical",
  "sahara",
  "salespitch",
  "seoul",
  "sharp",
  "show-cameo",
  "show-marquis",
  "show-plume",
  "show-soiree",
  "sidebar",
  "spark",
  "stockholm",
  "stripe",
  "swissgrid",
  "teacher",
  "thompson",
  "timelinevertical",
  "tokyo",
  "translatorcv",
  "uxtokens",
  "velvet",
  "vertex",
  "vertical",
  "vienna",
  "vitae",
  "vogue",
  "windsor",
  "writer",
  "zurich",
])

/** True when `public/thumbnails/<id>.webp` is known to exist. */
export function hasStaticThumbnail(templateId: string): boolean {
  return STATIC_THUMBNAIL_IDS.has(templateId)
}
