-- Freemium friction-point tracking
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FREE_DOWNLOAD_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FREE_AI_QUOTA_EXHAUSTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FREE_RESUME_LIMIT_HIT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FREE_COVER_LETTER_LIMIT_HIT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FREE_AI_ENDPOINT_BLOCKED';
