-- Migration: add_audit_actions_webhook
-- Created: 2026-05-08 19:45:01

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DISPUTE_CLOSED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FRAUD_WARNING';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROFILE_SYNCED_FROM_STRIPE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_CREATED_EXTERNAL';
