#!/usr/bin/env bash
# Usage: ./scripts/create-migration.sh <migration_name>
# Example: ./scripts/create-migration.sh add_plan_interval

set -e

if [ -z "$1" ]; then
  echo "Error: debes proporcionar un nombre para la migración"
  echo "Uso: ./scripts/create-migration.sh <nombre_migracion>"
  echo "Ejemplo: ./scripts/create-migration.sh add_email_verified"
  exit 1
fi

MIGRATION_NAME="$1"
TIMESTAMP=$(date +%Y%m%d%H%M%S)
MIGRATION_DIR="prisma/migrations/${TIMESTAMP}_${MIGRATION_NAME}"
LOCK_FILE="prisma/migrations/migration_lock.toml"

mkdir -p "$MIGRATION_DIR"

# Crear el archivo SQL vacío con comentario guía
cat > "$MIGRATION_DIR/migration.sql" << EOF
-- Migration: ${MIGRATION_NAME}
-- Created: $(date '+%Y-%m-%d %H:%M:%S')

-- Escribe aquí tu SQL. Ejemplos:
-- ALTER TABLE "User" ADD COLUMN "emailVerified" BOOLEAN NOT NULL DEFAULT false;
-- ALTER TABLE "User" ADD COLUMN "avatarUrl" TEXT;
-- CREATE INDEX "User_email_idx" ON "User"("email");

EOF

# Crear migration_lock.toml si no existe
if [ ! -f "$LOCK_FILE" ]; then
  cat > "$LOCK_FILE" << EOF
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
EOF
  echo "Creado: $LOCK_FILE"
fi

echo ""
echo "Migración creada en: $MIGRATION_DIR/migration.sql"
echo ""
echo "Abre el archivo y escribe el SQL necesario, luego haz commit y push."
echo "Al hacer deploy, se aplicará automáticamente via 'prisma migrate deploy'."
